"""Configuration package."""

from config.classes import (
    ClassCatalog,
    ClassDefinition,
    RoleDefinition,
    Slot,
    build_class_button_custom_id,
    build_role_button_custom_id,
    emoji_name,
    load_classes,
)
from config.polls import (
    CANCEL_CLOSE_CUSTOM_ID,
    KEY_PATTERN,
    REACTIONS_PER_MESSAGE,
    SELECT_OPTIONS_LIMIT,
    OptionDefinition,
    PollCatalog,
    PollDefinition,
    ProposalRejection,
    ProposalRules,
    build_clear_custom_id,
    build_close_custom_id,
    build_modal_custom_id,
    build_propose_custom_id,
    build_vote_custom_id,
    clean_name,
    load_catalog,
    slugify,
)
from config.settings import Settings, get_settings

__all__ = [
    "CANCEL_CLOSE_CUSTOM_ID",
    "KEY_PATTERN",
    "REACTIONS_PER_MESSAGE",
    "SELECT_OPTIONS_LIMIT",
    "ClassCatalog",
    "ClassDefinition",
    "OptionDefinition",
    "PollCatalog",
    "PollDefinition",
    "ProposalRejection",
    "ProposalRules",
    "RoleDefinition",
    "Settings",
    "Slot",
    "build_class_button_custom_id",
    "build_clear_custom_id",
    "build_close_custom_id",
    "build_modal_custom_id",
    "build_propose_custom_id",
    "build_role_button_custom_id",
    "build_vote_custom_id",
    "clean_name",
    "emoji_name",
    "get_settings",
    "load_catalog",
    "load_classes",
    "slugify",
]
